import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/providers";
import "react-toastify/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { SocketProvider } from "@/context/socketContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SocketProvider>{children}</SocketProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
