import { Geist, Geist_Mono } from "next/font/google";
import { Dashboard } from "@/components/Header";
import SideBar from "@/components/Sidebar";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard: Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isAuth, setisAuth] = useState('')
    useEffect(()=>{
        setisAuth(localStorage.getItem('user'))
    },[])
  return (
      <main
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="grid grid-cols-5 w-screen text-black bg-white ">
                    <SideBar />
                    <div className="col-span-4 h-screen overflow-y-auto bg-[#309689]/5 ">
                        <Dashboard />
                        {children}
                    </div>
                </main>
      <ToastContainer/>
      </main>
  );
}
