import { Geist, Geist_Mono } from "next/font/google";
import { Dashboard } from "@/components/Header";
import SideBar from "@/components/Sidebar";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard: Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="grid grid-cols-5 w-screen text-black bg-white ">
                    <SideBar />
                    <div className="col-span-4 h-screen overflow-y-auto bg-[#309689]/5 ">
                        <Dashboard />
                        {children}
                    </div>
                </main>
      </body>
    </html>
  );
}
